name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: ghcr.io/sing3demons/go-service:1.0.0

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup SHA
      run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Build the Docker image go
      run: docker build ./go-service --file ./go-service/Dockerfile --tag ghcr.io/sing3demons/go-service:${{ env.GITHUB_SHA }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Push to GitHub Container Registry
      uses: docker/build-push-action@v4
      with:
        context: ./go-service
        file: ./go-service/Dockerfile
        tags: ghcr.io/sing3demons/go-service:${{ env.GITHUB_SHA }}
        push: true

    - name: Echo the Docker image name
      run: echo ghcr.io/sing3demons/go-service:${{ env.GITHUB_SHA }}
