name: Docker Image CI
on:
  push:
    tags:
      - 'v*.*.*'

env:
  DOCKER_IMAGE: ghcr.io/sing3demons/go-service:1.0.0
  NODE_IMAGE: ghcr.io/sing3demons/node-service:1.0.0

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup SHA
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build ./go-service --file ./go-service/Dockerfile --tag ${{env.DOCKER_IMAGE}}
      - name: Build the Node Docker image
        run: docker build ./node_express --file ./node_express/Dockerfile --tag ${{env.NODE_IMAGE}}

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: ./go-service
          file: ./go-service/Dockerfile
          tags: ${{env.DOCKER_IMAGE}}
          push: true
      - name: Echo the Docker image name
        run: echo ${{env.DOCKER_IMAGE}}

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: ./node_express
          file: ./node_express/Dockerfile
          tags: ${{env.NODE_IMAGE}}
          push: true
      - name: Echo the Docker image name
        run: echo ${{env.NODE_IMAGE}}
