name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup SHA
      run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Build the Docker image go
      run: docker build . --file ./go-service/Dockerfile --tag ghcr.io/sing3demons/go-service:${{ env.GITHUB_SHA }}
    - name: Build the Docker image node
      run: docker build . --file ./node_express/Dockerfile --tag ghcr.io/sing3demons/node-service:${{ env.GITHUB_SHA }}

    - name: Login ghcr.io
      uses: docker/login-action@v1.8.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: true
    
    - name: Push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ghcr.io/sing3demons/devops-go:${{ env.GITHUB_SHA }}
        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/main' }}
      
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
